// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIdao2lwWVkUeLENobBtlV9NDNxwQhjtk',
    appId: '1:59601837642:web:63c03be7c9bef4dd7e10b3',
    messagingSenderId: '59601837642',
    projectId: 'fir-kucarpark-acea7',
    authDomain: 'fir-kucarpark-acea7.firebaseapp.com',
    storageBucket: 'fir-kucarpark-acea7.firebasestorage.app',
    measurementId: 'G-TPXPVVQS3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwIWEFdi_4YxYnh4FG1gGbbKwPaJyYVU',
    appId: '1:59601837642:android:eddc77bf305e21837e10b3',
    messagingSenderId: '59601837642',
    projectId: 'fir-kucarpark-acea7',
    storageBucket: 'fir-kucarpark-acea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHfV-zGUD74elsu7dchgTRmg_iaO0IvIs',
    appId: '1:59601837642:ios:84a23732005ebf2b7e10b3',
    messagingSenderId: '59601837642',
    projectId: 'fir-kucarpark-acea7',
    storageBucket: 'fir-kucarpark-acea7.firebasestorage.app',
    iosBundleId: 'com.example.kuCarparkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHfV-zGUD74elsu7dchgTRmg_iaO0IvIs',
    appId: '1:59601837642:ios:84a23732005ebf2b7e10b3',
    messagingSenderId: '59601837642',
    projectId: 'fir-kucarpark-acea7',
    storageBucket: 'fir-kucarpark-acea7.firebasestorage.app',
    iosBundleId: 'com.example.kuCarparkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIdao2lwWVkUeLENobBtlV9NDNxwQhjtk',
    appId: '1:59601837642:web:d39ef5417b4b37fe7e10b3',
    messagingSenderId: '59601837642',
    projectId: 'fir-kucarpark-acea7',
    authDomain: 'fir-kucarpark-acea7.firebaseapp.com',
    storageBucket: 'fir-kucarpark-acea7.firebasestorage.app',
    measurementId: 'G-KL18FK73DG',
  );
}
